package com.taiyitistmc.vanillaextra.datagen;

import com.taiyitistmc.vanillaextra.VanillaExtra;
import com.taiyitistmc.vanillaextra.common.init.ModBlocks;
import com.taiyitistmc.vanillaextra.common.init.ModEntities;
import com.taiyitistmc.vanillaextra.common.init.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModLanguageProviderZh extends LanguageProvider {

    public ModLanguageProviderZh(PackOutput output) {
        super(output, VanillaExtra.MODID, "zh_cn");
    }

    @Override
    protected void addTranslations() {
        add(ModBlocks.LAND_KELP.get(), "陆生海带");
        add(ModBlocks.LAND_KELP_PLANT.get(), "陆生海带");
        add(ModItems.DRIED_LAND_KELP.get(), "陆生海带干");
        add("itemGroup.vainllaextra.misc", "Vanilla Extra杂项");
        add("itemGroup.vainllaextra.food", "Vanilla Extra食物");
        add("itemGroup.vainllaextra.nature", "Vanilla Extra自然");
        add(ModBlocks.SAGO_PALM_LOG.get(), "西米棕榈原木");
        add(ModBlocks.SAGO_PALM_PLANKS.get(), "西米棕榈木板");
        add(ModBlocks.SAGO_PALM_SAPLING.get(), "西米棕榈树苗");
        add(ModBlocks.SAGO_PALM_LEAVES.get(), "西米棕榈树叶");
        add(ModBlocks.STRIPPED_SAGO_PALM_LOG.get(), "去皮西米棕榈原木");
        add(ModItems.SAGO.get(), "西米");
        add(ModItems.BACON.get(), "培根");
        add(ModItems.COOKED_BACON.get(), "熟培根");
        add(ModItems.BACON_AND_EGG.get(), "培根煎蛋");
        add(ModItems.WOLF_MEAT.get(), "狼肉");
        add(ModItems.COOKED_WOLF_MEAT.get(), "熟狼肉");
        add(ModItems.HORSE_MEAT.get(), "马肉");
        add(ModItems.COOKED_HORSE_MEAT.get(), "熟马肉");
        add(ModItems.SQUID_RAW.get(), "生鱿鱼");
        add(ModItems.SQUID_COOKED.get(), "熟鱿鱼");
        add(ModItems.BAT_WING.get(), "蝙蝠翼");
        add(ModItems.COOKED_BAT_WING.get(), "熟蝙蝠翼");
        add(ModItems.LLAMA_MEAT.get(), "羊驼肉");
        add(ModItems.COOKED_LLAMA_MEAT.get(), "熟羊驼肉");
        add(ModItems.HUMAN_MEAT.get(), "人肉");
        add(ModItems.COOKED_HUMAN_MEAT.get(), "熟人肉");
        add(ModBlocks.PEACH_LEAVES.get(), "桃树叶");
        add(ModBlocks.PEACH_LOG.get(), "桃树原木");
        add(ModBlocks.PEACH_SAPLING.get(), "桃树苗");
        add(ModBlocks.PEACH_PLANKS.get(), "桃木板");
        add(ModItems.PEACH.get(), "桃子");
        add(ModItems.PEACH_WOOD_SWORD.get(), "桃木剑");
        add(ModEntities.BLACK_DOG.get(), "黑狗");
        add(ModItems.BLACK_DOG_SPAWN_EGG.get(), "黑狗刷怪蛋");
        add(ModItems.BLACK_DOG_BLOOD.get(), "黑狗血");
        add(ModEntities.FRIENDLY_ZOMBIE.get(), "友好的僵尸");
        add(ModItems.FRIENDLY_ZOMBIE_SPAWN_EGG.get(), "友好的僵尸刷怪蛋");
        add(ModEntities.FRIENDLY_SKELETON.get(), "友好的骷髅");
        add(ModItems.FRIENDLY_SKELETON_SPAWN_EGG.get(), "友好的骷髅刷怪蛋");
        add(ModBlocks.IRON_ORE_STEM.get(), "铁矿石茎");
        add(ModBlocks.ATTACHED_IRON_ORE_STEM.get(), "附着的铁矿石茎");
        add(ModItems.IRON_ORE_SEEDS.get(), "铁矿石种子");
        add(ModBlocks.COAL_ORE_STEM.get(), "煤矿石茎");
        add(ModBlocks.ATTACHED_COAL_ORE_STEM.get(), "附着的煤矿石茎");
        add(ModItems.COAL_ORE_SEEDS.get(), "煤矿石种子");
        add(ModBlocks.GOLD_ORE_STEM.get(), "金矿石茎");
        add(ModBlocks.ATTACHED_GOLD_ORE_STEM.get(), "附着的金矿石茎");
        add(ModItems.GOLD_ORE_SEEDS.get(), "金矿石种子");
        add(ModBlocks.LAPIS_ORE_STEM.get(), "青金石茎");
        add(ModBlocks.ATTACHED_LAPIS_ORE_STEM.get(), "附着的青金石茎");
        add(ModItems.LAPIS_ORE_SEEDS.get(), "青金石种子");
        add(ModBlocks.DIAMOND_ORE_STEM.get(), "钻石茎");
        add(ModBlocks.ATTACHED_DIAMOND_ORE_STEM.get(), "附着的钻石茎");
        add(ModItems.DIAMOND_ORE_SEEDS.get(), "钻石种子");
        add(ModBlocks.REDSTONE_ORE_STEM.get(), "红石茎");
        add(ModBlocks.ATTACHED_REDSTONE_ORE_STEM.get(), "附着的红石茎");
        add(ModItems.REDSTONE_ORE_SEEDS.get(), "红石种子");
        add(ModBlocks.EMERALD_ORE_STEM.get(), "绿宝石茎");
        add(ModBlocks.ATTACHED_EMERALD_ORE_STEM.get(), "附着的绿宝石茎");
        add(ModItems.EMERALD_ORE_SEEDS.get(), "绿宝石种子");
        add(ModBlocks.COPPER_ORE_STEM.get(), "铜矿石茎");
        add(ModBlocks.ATTACHED_COPPER_ORE_STEM.get(), "附着的铜矿石茎");
        add(ModItems.COPPER_ORE_SEEDS.get(), "铜矿石种子");
        add(ModItems.ENDERMAN_MEAT.get(), "末影人肉");
        add(ModItems.COOKED_ENDERMAN_MEAT.get(), "熟末影人肉");
        add(ModBlocks.ANCIENT_DEBRIS_STEM.get(), "远古残骸茎");
        add(ModBlocks.ATTACHED_ANCIENT_DEBRIS_STEM.get(), "附着的远古残骸茎");
        add(ModItems.ANCIENT_DEBRIS_SEEDS.get(), "远古残骸种子");
        add(ModBlocks.AMETHYST_STEM.get(), "紫水晶茎");
        add(ModBlocks.ATTACHED_AMETHYST_STEM.get(), "附着的紫水晶茎");
        add(ModItems.AMETHYST_SEEDS.get(), "紫水晶种子");
        add(ModEntities.WILD_BOAR.get(), "野猪");
        add(ModItems.WILD_BOAR_SPAWN_EGG.get(), "野猪刷怪蛋");
        add(ModItems.WILD_BOAR_MEAT.get(), "野猪肉");
        add(ModItems.COOKED_WILD_BOAR_MEAT.get(), "熟野猪肉");
        add(ModItems.OCELOT_MEAT.get(), "豹猫肉");
        add(ModItems.COOKED_OCELOT_MEAT.get(), "熟豹猫肉");
        add(ModItems.SPIDER_LEG.get(), "蜘蛛腿");
        add(ModItems.COOKED_SPIDER_LEG.get(), "熟蜘蛛腿");
        add(ModBlocks.COAL_TREE_LOG.get(), "煤炭树原木");
        add(ModBlocks.COAL_TREE_LEAVES.get(), "煤炭树树叶");
        add(ModBlocks.COAL_TREE_SAPLING.get(), "煤炭树树苗");
        add(ModBlocks.COPPER_TREE_LOG.get(), "铜矿树原木");
        add(ModBlocks.COPPER_TREE_LEAVES.get(), "铜矿树树叶");
        add(ModBlocks.COPPER_TREE_SAPLING.get(), "铜矿树树苗");
        add(ModBlocks.DIAMOND_TREE_LOG.get(), "钻石树原木");
        add(ModBlocks.DIAMOND_TREE_LEAVES.get(), "钻石树树叶");
        add(ModBlocks.DIAMOND_TREE_SAPLING.get(), "钻石树树苗");
        add(ModBlocks.EMERALD_TREE_LOG.get(), "绿宝石树原木");
        add(ModBlocks.EMERALD_TREE_LEAVES.get(), "绿宝石树树叶");
        add(ModBlocks.EMERALD_TREE_SAPLING.get(), "绿宝石树树苗");
        add(ModBlocks.GOLD_TREE_LOG.get(), "金矿石树原木");
        add(ModBlocks.GOLD_TREE_LEAVES.get(), "金矿石树树叶");
        add(ModBlocks.GOLD_TREE_SAPLING.get(), "金矿石树树苗");
        add(ModBlocks.IRON_TREE_LOG.get(), "铁矿石树原木");
        add(ModBlocks.IRON_TREE_LEAVES.get(), "铁矿石树树叶");
        add(ModBlocks.IRON_TREE_SAPLING.get(), "铁矿石树树苗");
        add(ModBlocks.LAPIS_TREE_LOG.get(), "青金石树原木");
        add(ModBlocks.LAPIS_TREE_LEAVES.get(), "青金石树树叶");
        add(ModBlocks.LAPIS_TREE_SAPLING.get(), "青金石树树苗");
        add(ModBlocks.REDSTONE_TREE_LOG.get(), "红石树原木");
        add(ModBlocks.REDSTONE_TREE_LEAVES.get(), "红石树树叶");
        add(ModBlocks.REDSTONE_TREE_SAPLING.get(), "红石树树苗");
        add(ModBlocks.QUARTZ_TREE_LOG.get(), "石英树原木");
        add(ModBlocks.QUARTZ_TREE_LEAVES.get(), "石英树树叶");
        add(ModBlocks.QUARTZ_TREE_SAPLING.get(), "石英树树苗");
        add(ModBlocks.NETHERITE_TREE_LOG.get(), "下界合金树原木");
        add(ModBlocks.NETHERITE_TREE_LEAVES.get(), "下界合金树树叶");
        add(ModBlocks.NETHERITE_TREE_SAPLING.get(), "下界合金树树苗");
        add(ModEntities.FRIENDLY_SPIDER.get(), "友好的蜘蛛");
        add(ModItems.FRIENDLY_SPIDER_SPAWN_EGG.get(), "友好的蜘蛛刷怪蛋");
        add("advancements.vanillaextra.story.obtain_land_kelp.title", "特殊的海带,陆生海带");
        add("advancements.vanillaextra.story.obtain_land_kelp.description", "一种登上陆地的特殊海带,可以长到6格高,是美味的农作物");
        add("advancements.vanillaextra.story.obtain_dried_land_kelp.title", "美味的陆生海带干,一种食物");
        add("advancements.vanillaextra.story.obtain_dried_land_kelp.description", "烤制的陆生海带干，非常美味");
    }
}
